require: rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'Rakefile'
    - '**/*.rake'
    - 'db/migrate/20240202172559_add_service_name_to_active_storage_blobs.active_storage.rb'
    - 'db/migrate/20240202172560_create_active_storage_variant_records.active_storage.rb'
    - 'db/migrate/20240202172561_remove_not_null_on_active_storage_blobs_checksum.active_storage.rb'
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Layout/LineLength:
  Exclude:
    - 'Gemfile'
  Max: 80

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Exclude:
    - 'db/migrate/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'test/**/*.rb'
  ExcludedMethods:
    - 'class_methods'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/**/*_controller.rb'
    - 'db/migrate/**/*.rb'

Style/ClassAndModuleChildren:
  Enabled: false
