require: rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'bin/*'
    - 'Rakefile'
    - '**/*.rake'
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Layout/LineLength:
  Exclude:
    - 'Gemfile'
  Max: 80

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/**/*_controller.rb'
    - 'db/migrate/**/*.rb'

Style/ClassAndModuleChildren:
  Enabled: false
