require: rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'bin/*'
    - 'Rakefile'
    - '**/*.rake'
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

Style/ClassAndModuleChildren:
  Enabled: false
