require: rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'bin/*'
    - 'Rakefile'
    - '**/*.rake'
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'
